apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: longdd90jp/aws-esc:todo-app.1.2
          env:
            - name: ACTIVE_PROFILE
              value: k8s
            - name: SERVER_PORT
              value: "8085"
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER_NAME
              value: "root"
            - name: DB_PASSWORD
              value: "root12345"
            - name: COGNITO_PROVIDER_URL
              value: "http://keycloak:8080/realms/stratospheric"
            - name: AWS_END_POINT
              value: "localstack"
          ports:
            - name: http
              containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  selector:
    app: todo-app
  type: ClusterIP