server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/stratospheric
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root12345}
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: spring-boot-application
            clientSecret: 27b07baf-53ba-42c6-b11f-6384769cada3
            scope: openid
        provider:
          cognito:
            issuerUri: ${COGNITO_PROVIDER_URL:http://localhost:8080/auth/realms/stratospheric}
  thymeleaf:
    cache: false
#    prefix: file:src/main/resources/templates/
  web:
    resources:
#      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  jpa:
    show-sql: true
  cloud:
    aws:
      credentials:
        secret-key: foo
        access-key: bar
      endpoint: http://${AWS_END_POINT:localhost}:4566
      region:
        static: us-east-1

management:
  cloudwatch:
    metrics:
      export:
        enabled: false

custom:
  internal-broker: true
  sharing-queue: ${TODO_SHARING_QUEUE_NAME:stratospheric-todo-sharing}
  auto-confirm-collaborations: true
  web-socket-relay-use-ssl: false
  provide-test-todo-controller: false
  use-cognito-as-identity-provider: false
  confirm-email-from-address: ${NO_REPLY_EMAIL:noreply@stratospheric.dev}
  environment: local