server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/stratospheric
    username: ${DB_USER_NAME:admin}
    password: ${DB_PASSWORD:admin12345}
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid,profile,email
            clientName: ${COGNITO_CLIENT_NAME}
        provider:
          cognito:
            issuerUri: ${COGNITO_PROVIDER_URL}
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
  jpa:
    show-sql: false
  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        endpoint: https://sqs.us-east-1.amazonaws.com/784965684233
      dynamodb:
        endpoint: https://dynamodb.us-east-1.amazonaws.com
      ses:
        endpoint: https://email.us-east-1.amazonaws.com
  activemq:
    password: ${MQ_PASSWORD:admin}
    user: ${MQ_USER:admin}
    broker-url: ${MQ_BROKER_URL:localhost}:${MQ_BROKER_PORT:61613}

management:
  cloudwatch:
    metrics:
      export:
        enabled: false

custom:
  sharing-queue: ${TODO_SHARING_QUEUE_NAME:stratospheric-todo-sharing}
  auto-confirm-collaborations: true
  web-socket-relay-use-ssl: false
  provide-test-todo-controller: false
  use-cognito-as-identity-provider: true
  confirm-email-from-address: ${NO_REPLY_EMAIL:noreply@stratospheric.dev}