server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stratospheric
    username: stratospheric
    password: stratospheric
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 1r6ninjt34cv32epb6qnc6hhqb
            clientSecret: udh7163u697s9t7eq6q2ktnb165e1887rhseg0g2t0nsvbd8lvs
            scope: openid,profile,email
            clientName: todo-spring-boot
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_T7GTAxqF4
  thymeleaf:
    cache: false
#    prefix: file:src/main/resources/templates/
  web:
    resources:
#      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  jpa:
    show-sql: true
  cloud:
    aws:
      credentials:
        secret-key: foo
        access-key: bar
      endpoint: http://localhost:4566
      region:
        static: us-east-1
  activemq:
    password: admin
    user: admin
    broker-url: localhost:61613

management:
  cloudwatch:
    metrics:
      export:
        enabled: false

custom:
  web-socket-relay-use-ssl: false
  auto-confirm-collaborations: true
  provide-test-todo-controller: true
  use-cognito-as-identity-provider: true
  environment: local