server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stratospheric
    username: stratospheric
    password: stratospheric
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 1r6ninjt34cv32epb6qnc6hhqb
            clientSecret: udh7163u697s9t7eq6q2ktnb165e1887rhseg0g2t0nsvbd8lvs
            scope: openid,profile,email
            clientName: todo-spring-boot
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_T7GTAxqF4
#  security:
#    oauth2:
#      client:
#        registration:
#          cognito:
#            clientId: spring-boot-application
#            clientSecret: 27b07baf-53ba-42c6-b11f-6384769cada3
#            scope: openid
#        provider:
#          cognito:
#            issuerUri: http://localhost:8888/auth/realms/stratospheric
  thymeleaf:
    cache: false
#    prefix: file:src/main/resources/templates/
  web:
    resources:
#      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  jpa:
    show-sql: true
  cloud:
    aws:
      credentials:
        secret-key: ${SECRET_KEY:foo}
        access-key: ${ACCESS_KEY:bar}
      region:
        static: us-east-1
      sqs:
        endpoint: https://sqs.us-east-1.amazonaws.com/784965684233
      dynamodb:
        endpoint: https://dynamodb.us-east-1.amazonaws.com
      ses:
        endpoint: https://email.us-east-1.amazonaws.com
  activemq:
    password: ${MQ_PASSWORD:admin}
    user: ${MQ_USER:admin}
    broker-url: ${MQ_BROKER_URL:localhost:61613}

management:
  cloudwatch:
    metrics:
      export:
        enabled: false

custom:
#  web-socket-relay-use-ssl: false
#  auto-confirm-collaborations: true
#  provide-test-todo-controller: true
#  use-cognito-as-identity-provider: true
#  environment: local
  sharing-queue: ${TODO_SHARING_QUEUE_NAME:stratospheric-todo-sharing}
  auto-confirm-collaborations: true
  web-socket-relay-use-ssl: false
  provide-test-todo-controller: false
  use-cognito-as-identity-provider: true
  confirm-email-from-address: ${NO_REPLY_EMAIL:noreply@stratospheric.dev}